"""Merge request_date into created_at

Revision ID: 38e037ee5657
Revises: 3ee53ca09fc8
Create Date: 2025-08-01 11:53:54.991763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e037ee5657'
down_revision = '3ee53ca09fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_column('request_date')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
