"""Added request date field to my Request Models

Revision ID: 3ee53ca09fc8
Revises: 75071e9fb567
Create Date: 2025-08-01 11:38:05.833421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee53ca09fc8'
down_revision = '75071e9fb567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_column('request_date')

    # ### end Alembic commands ###
